import {Asset,Entity,Vec3,Quat,BoundingBox,type Application,type ContainerResource,type AnimTrack,type RenderComponent} from 'playcanvas';
import {audioLevel} from '../ui/AudioSettings';
import {assetUrl} from '../editor/AssetUrls';
import {material,primitives} from './primitives';
import {POND} from './Outdoors';
import {FishingRound,type PullDirection} from '../systems/FishingRound';
import {flexibleRod} from './FishingRod';
import {saveId} from '../systems/saveId';
import type {createCharacter} from '../components/CharacterVisual';
import type {IsometricCamera} from './IsometricCamera';
import type {ProgressStore,RevealReceipt} from '../systems/ProgressStore';
import {DUMPLINGS} from '../data/collection';
import {createDumpling} from './dumplingVisual';
import {SquishyRevealVfx} from './SquishyRevealVfx';
import {SquishyRevealAudio} from './SquishyRevealAudio';
import {SQUISHY_PRESENTATION} from '../data/squishyPresentation';
const FISH=[['goldfish','Golden Gill'],['puffer','Pudding Puffer'],['betta','Ribbon Betta'],['armoredcatfish','Pebble Catfish']];
export class Fishing{
 readonly round=new FishingRound();readonly root:Entity;readonly ready:Promise<void>;
 private rod:Entity;private flexible?:ReturnType<typeof flexibleRod>;private line:Entity;private bobber:Entity;private ripple:Entity;private wakes:Entity[]=[];private fishes:Entity[]=[];private fishModels:Entity[]=[];
 private reward:Entity|null=null;private receipt:RevealReceipt|null=null;private vfx:SquishyRevealVfx;private audio=new SquishyRevealAudio();private splash:HTMLAudioElement;private prev='';private lastClip='';private settle=0;private startPoint=new Vec3();private caught=false;private saveError='';private side=0;private fishPoint=POND.bobber.clone();private lastFish=POND.bobber.clone();private landingPoint=POND.bobber.clone();private events=new AbortController();private heldClick=false;
 readonly panel=document.createElement('section');private cancel=document.createElement('button');private button=document.createElement('button');private copy=document.createElement('p');private meter=document.createElement('progress');private tension=document.createElement('progress');private gauges=document.createElement('div');private controls=document.createElement('div');private left=document.createElement('button');private right=document.createElement('button');private status=document.createElement('span');private tip=document.createElement('small');onFinish=()=>{};onReward=()=>{};
 get active(){return this.round.phase!=='idle';}
 constructor(private app:Application,parent:Entity,private character:ReturnType<typeof createCharacter>,private camera:IsometricCamera,private save:ProgressStore){
  this.splash=new Audio(assetUrl('assets/outdoors/pond-splash.mp3'));this.splash.preload='auto';
  this.root=new Entity('Pond fishing presentation',app);parent.addChild(this.root);const shape=primitives(app,this.root),wood=material('Fishing rod cork','#ac8762'),red=material('Bobber coral','#f1958c'),cream=material('Fishing cream','#fff1d7');
  this.rod=new Entity('Hand fitted fishing rod',app);this.root.addChild(this.rod);const r=primitives(app,this.rod);r('Cork grip','cylinder',[0,.12,0],[.07,.24,.07],wood);r('Slender rod','cylinder',[0,.98,0],[.026,1.7,.026],cream,false);r('Reel','sphere',[.05,.26,0],[.13,.15,.12],wood);
  this.line=shape('Fishing line','cylinder',[0,0,0],[.008,1,.008],cream,false);this.bobber=shape('Pond bobber','sphere',POND.bobber.toArray() as [number,number,number],[.13,.17,.13],red,false);const foam=material('Ripple foam','#bfe4d8');this.ripple=shape('Bobber water ripple','cylinder',[0,0,0],[.4,.008,.4],foam,false);for(let i=0;i<3;i++)this.wakes.push(shape('Fish wake '+i,'sphere',[0,0,0],[.06,.025,.06],foam,false));this.vfx=new SquishyRevealVfx(app,this.root);this.root.enabled=false;
  this.setupControls();
  const rodReady=this.load('fishingrod_lvl1').then(res=>{const e=res.instantiateRenderEntity({castShadows:true}),bounds=this.bounds(e),scale=1.82/(bounds.halfExtents.y*2),pivot=new Entity('Rod normalization',app);this.rod.addChild(pivot);pivot.addChild(e);pivot.setLocalScale(scale,scale,scale);pivot.setLocalPosition(-bounds.center.x*scale,-(bounds.center.y-bounds.halfExtents.y)*scale,-bounds.center.z*scale);this.flexible=flexibleRod(app,this.rod,e);for(const name of ['Cork grip','Slender rod','Reel'])this.rod.findByName(name)!.enabled=false;});
  this.ready=Promise.all(FISH.map(async([file],i)=>{const res=await this.load(file),e=res.instantiateRenderEntity({castShadows:true}),bounds=this.bounds(e),anchor=new Entity(file,app);this.root.addChild(anchor);const normalization=new Entity('Fish size and origin',app);anchor.addChild(normalization);normalization.addChild(e);const scale=.8/Math.max(bounds.halfExtents.x*2,bounds.halfExtents.y*2,bounds.halfExtents.z*2);normalization.setLocalScale(scale,scale,scale);normalization.setLocalPosition(-bounds.center.x*scale,-bounds.center.y*scale,-bounds.center.z*scale);const tracks=res.animations.map(a=>a.resource as AnimTrack);e.addComponent('anim',{activate:true});e.anim!.assignAnimation('Swim',tracks.find(a=>/swim/i.test(a.name))??tracks[0]);e.anim!.assignAnimation('Caught',tracks.find(a=>a.name.includes('Out_Of_Water'))??tracks[0]);e.anim!.baseLayer!.play('Swim');this.fishModels[i]=e;anchor.enabled=false;return anchor;})).then(async f=>{this.fishes=f;await rodReady;});
 }
 private load(file:string){return new Promise<ContainerResource&{animations:Asset[]}>((resolve,reject)=>{const a=new Asset(file,'container',{url:assetUrl('assets/outdoors/'+file+'.glb')});a.once('load',()=>resolve(a.resource as ContainerResource&{animations:Asset[]}));a.once('error',reject);this.app.assets.add(a);this.app.assets.load(a);});}
 private bounds(e:Entity){const b=new BoundingBox();let first=true;for(const r of e.findComponents('render') as RenderComponent[])for(const m of r.meshInstances){if(first){b.copy(m.aabb);first=false;}else b.add(m.aabb);}return b;}
 private setupControls(){
  this.panel.id='fishing-panel';this.panel.hidden=true;this.panel.setAttribute('aria-label','Pond fishing');this.copy.setAttribute('aria-live','polite');this.button.id='fish-action';this.left.id='fish-left';this.right.id='fish-right';this.meter.max=this.tension.max=1;this.meter.setAttribute('aria-label','Distance reeled in');this.tension.setAttribute('aria-label','Line tension');this.gauges.className='fish-gauges';this.controls.className='fish-controls';this.status.className='fish-status';this.tip.className='fish-tip';
  for(const [label,meter] of [['Closer to shore',this.meter],['Line tension',this.tension]] as const){const text=document.createElement('label');text.textContent=label;text.append(meter);this.gauges.append(text);}
  for(const b of [this.button,this.cancel,this.left,this.right])b.type='button';this.cancel.textContent='Leave pond';this.left.textContent='← PULL';this.right.textContent='PULL →';this.left.setAttribute('aria-label','Hold to pull left');this.right.setAttribute('aria-label','Hold to pull right');this.controls.append(this.left,this.button,this.right);this.panel.append(this.status,this.copy,this.gauges,this.controls,this.tip,this.cancel);document.querySelector('#game')!.append(this.panel);
  const signal=this.events.signal,release=()=>this.round.releaseControls();
  this.button.addEventListener('click',()=>{if(this.heldClick){this.heldClick=false;return;}this.press();},{signal});this.cancel.addEventListener('click',()=>this.end(),{signal});
  for(const [b,side] of [[this.button,0],[this.left,-1],[this.right,1]] as const){const up=()=>{if(side===0)this.round.holdReel(false);else if(this.round.direction===side)this.round.steer(0);};b.addEventListener('pointerdown',e=>{if(this.round.phase!=='reel'){if(side===0)this.heldClick=false;return;}b.setPointerCapture(e.pointerId);if(side===0){this.heldClick=true;this.round.holdReel(true);}else this.round.steer(side);},{signal});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,up,{signal});}
  window.addEventListener('blur',release,{signal});document.addEventListener('visibilitychange',()=>{if(document.hidden)release();},{signal});
  window.addEventListener('keydown',e=>{if(!this.active||!['Space','ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code))return;e.preventDefault();if(e.code==='Space'){if(this.round.phase==='reel')this.round.holdReel(true);else if(!e.repeat)this.press();}else this.round.steer(['ArrowLeft','KeyA'].includes(e.code)?-1:1);},{signal});window.addEventListener('keyup',e=>{if(!this.active)return;if(e.code==='Space'){e.preventDefault();this.round.holdReel(false);}if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code))this.round.steer(0);},{signal});
 }
 start(){if(this.active||this.character.placeholder.enabled)return;this.round.start(saveId());this.root.enabled=true;this.panel.hidden=false;this.prev=this.lastClip='';this.settle=0;this.side=0;this.heldClick=false;this.startPoint.copy(this.character.player.getPosition());this.receipt=null;this.caught=false;this.saveError='';this.reward?.destroy();this.reward=null;this.camera.beginChore(POND.stand,POND.bobber);this.character.animator.setWorkClip('Fishing_Idle',POND.bobber);}
 press(){if(this.round.phase==='miss'){this.end();this.start();return;}if(this.round.phase==='catch'){if(this.saveError){this.catchReward();return;}if(this.receipt){this.end();return;}this.round.step('release');return;}if(this.settle>=.7)this.round.tap();}
 update(dt:number){if(!this.active)return;if(document.hidden){this.round.releaseControls();this.audio.stop();return;}this.settle+=dt;const blend=Math.min(1,this.settle/.7),ease=blend*blend*(3-2*blend);this.character.player.setPosition(new Vec3().lerp(this.startPoint,POND.stand,ease));this.round.update(dt);const r=this.round;
  if(!this.active){this.end();return;}
  if(this.prev!==r.phase){this.prev=r.phase;if(r.phase==='bite')this.audio.lid();if(r.phase==='wait'||r.phase==='release'){this.splash.currentTime=0;this.splash.volume=.16*audioLevel('effects');void this.splash.play().catch(()=>{});}if(r.phase==='catch'){this.landingPoint.copy(this.fishPoint);this.fishModels[r.fishIndex]?.anim!.baseLayer!.play('Caught');this.catchReward();}if(r.phase==='reel')this.fishModels[r.fishIndex]?.anim!.baseLayer!.play('Swim');}
  const clip=r.phase==='cast'?'Fishing_Cast':r.phase==='bite'?'Fishing_Bite':r.phase==='reel'?(r.direction<0?'Fishing_Left':r.direction>0?'Fishing_Right':r.reeling?'Fishing_Reeling':'Fishing_Idle'):r.phase==='catch'?'Fishing_Catch':'Fishing_Idle';if(clip!==this.lastClip){this.lastClip=clip;this.character.animator.setWorkClip(clip,POND.bobber);}
  this.updatePanel();this.present(dt);
 }
 private updatePanel(){const r=this.round,fish=this.receipt?DUMPLINGS.find(d=>d.id===this.receipt!.dumplingId):null;
  const cue=r.warning?'LET GO · give the line a rest':r.tired?'Getting tired! Hold to reel it home':r.pullSide?(r.desiredDirection<0?'← PULL LEFT':'PULL RIGHT →')+' · hold REEL too':r.reeling?'Nice and steady…':'Hold REEL to bring it closer';
  const text:Record<string,string>={prepare:'Cast a line. Who is swimming below?',cast:'There goes the bobber!',wait:'Watch for the bobber to dip…',bite:'A bite! Tap HOOK!',reel:cue,catch:fish?`${fish.name} · ${fish.rarity} · ${this.receipt!.isNew?'NEW!':'DUPLICATE'} · Saved to your collection ♡`:`${FISH[r.fishIndex][1]}! Say hello, then let it swim home.`,release:'Back to the pond. Thanks, little friend!',miss:r.missReason};
  const words=this.saveError||text[r.phase];if(this.copy.textContent!==words)this.copy.textContent=words;this.status.textContent=r.phase==='reel'?(r.tired?'Sleepy fish':r.pullSide?'Fish is darting!':'Little pond adventure'):'Little pond adventure';this.button.textContent=({idle:'',prepare:'CAST',cast:'Casting…',wait:'Waiting…',bite:'HOOK!',reel:r.reeling?'REELING…':'HOLD REEL',catch:this.receipt?'Keep squishy':'Release fish ♡',release:'Swimming home…',miss:'Try again'})[r.phase];if(this.saveError)this.button.textContent='Retry saving';
  this.button.disabled=['cast','wait','release'].includes(r.phase)||this.settle<.7;this.gauges.hidden=this.left.hidden=this.right.hidden=r.phase!=='reel';this.meter.value=r.progress;this.tension.value=r.tension;this.panel.dataset.warning=String(r.warning);this.button.dataset.held=String(r.reeling);this.left.dataset.cue=String(r.desiredDirection===-1);this.right.dataset.cue=String(r.desiredDirection===1);this.left.dataset.held=String(r.direction===-1);this.right.dataset.held=String(r.direction===1);this.tip.textContent=r.phase==='reel'?'Hold to reel • Pull against the fish • Let go to relax':r.phase==='prepare'?'Tap to cast, then tap when a fish bites.':'';
 }
 private present(dt:number){const r=this.round;this.lastFish.copy(this.fishPoint);this.fishPoint.copy(POND.bobber);
  if(r.phase==='reel'){const near=new Vec3(-4.85,.16,-10.35),far=POND.bobber;this.fishPoint.lerp(near,far,r.distance);const target=r.pullSide*.68+Math.sin(r.fightTime*2)*.13;this.side+=(target-this.side)*Math.min(1,dt*3);const screenRight=this.camera.entity.right.clone();screenRight.y=0;screenRight.normalize();this.fishPoint.add(screenRight.mulScalar(this.side));this.fishPoint.y=.15+Math.sin(r.total*8)*.025;}
  const hands=this.character.animator.snapshot().hands;if(hands.length===2){const hand=new Vec3(...hands[1]);this.rod.setPosition(hand);const tip=new Vec3().lerp(hand,this.fishPoint,.58);tip.y+=1.35+(r.phase==='cast'?Math.sin(r.elapsed/1.93*Math.PI)*.7:0);this.rod.setRotation(new Quat().setFromDirections(Vec3.UP,tip.sub(hand).normalize()));}
  this.flexible?.update(r.phase==='reel'?r.tension*.30+(r.pullSide?Math.sin(r.total*18)*.018:0):.015,dt);this.rod.enabled=!['catch','release'].includes(r.phase);const rodTip=this.flexible?.tip()??this.rod.getWorldTransform().transformPoint(new Vec3(0,1.82,0));let bob=this.fishPoint.clone();
  if(r.phase==='wait'){const twitch=Math.max(0,1-Math.abs(r.elapsed-1.05)/.22);bob.y-=twitch*.035;}bob.y+=r.phase==='bite'?-.08+Math.sin(r.elapsed*24)*.04:Math.sin(r.total*3)*.025;
  if(r.phase==='prepare')bob.copy(rodTip).add(new Vec3(0,-.35,0));if(r.phase==='cast'){const t=Math.min(1,r.elapsed/1.5);bob.lerp(rodTip,bob,t);bob.y+=Math.sin(t*Math.PI)*1.3;}
  this.bobber.setPosition(bob);this.bobber.enabled=!['catch','release'].includes(r.phase);this.ripple.enabled=['wait','bite','reel'].includes(r.phase);this.ripple.setPosition(bob.x,.112,bob.z);const ripple=.25+(r.phase==='bite'?r.elapsed*2%1:r.elapsed%1.5)*.35;this.ripple.setLocalScale(ripple,.007,ripple);
  this.wakes.forEach((w,i)=>{w.enabled=r.phase==='reel';const t=(r.total*2+i/3)%1;w.setPosition(bob.x+Math.sin(i*2.1+r.total)*t*.25,.12+Math.sin(t*Math.PI)*(r.pullSide?.18:.05),bob.z+Math.cos(i*2.1+r.total)*t*.25);const s=(1-t)*.07;w.setLocalScale(s,s*.7,s);});
  const delta=bob.clone().sub(rodTip);this.line.setPosition(new Vec3().lerp(bob,rodTip,.5));this.line.setRotation(new Quat().setFromDirections(Vec3.UP,delta.clone().normalize()));this.line.setLocalScale(.008,delta.length(),.008);this.line.enabled=!['catch','release'].includes(r.phase);
  const reward=this.receipt?this.reward:this.fishes[r.fishIndex];this.fishes.forEach((f,i)=>f.enabled=!this.receipt&&i===r.fishIndex&&['reel','catch','release'].includes(r.phase));
  if(r.phase==='reel'){const fish=this.fishes[r.fishIndex];fish.setLocalScale(.65,.65,.65);fish.setPosition(this.fishPoint);const move=this.fishPoint.clone().sub(this.lastFish);if(move.lengthSq()>.000001)fish.setEulerAngles(0,Math.atan2(move.x,move.z)*180/Math.PI,Math.sin(r.total*7)*6);}
  if(reward&&['catch','release'].includes(r.phase)){const t=Math.min(1,r.elapsed/(r.phase==='release'?1:1.2)),from=r.phase==='release'?POND.bobber:this.landingPoint,to=new Vec3(-5.55,1.55,-10.65);if(!this.receipt)reward.setLocalScale(1,1,1);reward.setPosition(new Vec3().lerp(r.phase==='release'?to:from,r.phase==='release'?from:to,t));reward.rotateLocal(0,dt*35,0);if(this.receipt){this.vfx.root.setPosition(to.x,to.y+.4,to.z-.3);this.vfx.update(r.elapsed,false);}}
 }
 private catchReward(){if(this.caught)return;this.caught=true;if(this.round.catchKind==='squishy'){try{this.receipt=this.save.catchFishingSquishy(this.round.id);this.saveError='';const d=DUMPLINGS.find(d=>d.id===this.receipt!.dumplingId)!;this.reward=createDumpling(this.app,this.root,d);this.reward.setLocalScale(.65,.65,.65);this.vfx.configure(d.rarity);this.audio.celebrate(SQUISHY_PRESENTATION[d.rarity].notes);this.onReward();}catch{this.saveError='Your squishy has not saved yet. Tap Retry saving.';this.caught=false;}}else this.audio.celebrate([659,784]);}
 end(){this.round.step('idle');this.panel.hidden=true;this.root.enabled=false;this.vfx.hide();this.audio.stop();this.splash.pause();this.character.animator.setWorkClip(null);this.camera.endChore();this.onFinish();}
 snapshot(){const r=this.round;return{phase:r.phase,catchKind:r.catchKind,fish:r.fishIndex,receipt:this.receipt,loadedFish:this.fishes.length,tension:r.tension,progress:r.progress,energy:r.energy,pull:r.desiredDirection,reeling:r.reeling,direction:r.direction,fightTime:r.fightTime,rod:this.rod.getPosition().toArray(),bobber:this.bobber.getPosition().toArray()};}
 destroy(){this.events.abort();this.end();this.panel.remove();this.vfx.destroy();this.root.destroy();this.audio.destroy();}
}
