import {mkdir,writeFile} from 'node:fs/promises';
import {browser,page,context,dev,sleep,errors} from './store-test-helpers.mjs';
const out=process.env.EVIDENCE||'artifacts/performance-before';await mkdir(out,{recursive:true});
await context.addInitScript(()=>{if(!localStorage.getItem('production-fixture')){for(const key of ['progress.v1','daily.v1'])localStorage.setItem('arianna.'+key,localStorage.getItem('dumpling.editorMigration.'+key));localStorage.setItem('production-fixture','yes');}});
try{
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:5191/dist/index.html');await page.waitForFunction(()=>window.__roomTest?.snapshot().characterLoaded);await sleep(3000);
 await page.evaluate(async()=>{const pc=await import('playcanvas');window.auditApp=pc.Application.getApplication();const a=window.auditApp;let u=0,r=0;window.auditTimes={update:0,render:0};a.on('frameupdate',()=>u=performance.now());a.on('framerender',()=>window.auditTimes.update=performance.now()-u);a.on('prerender',()=>r=performance.now());a.on('postrender',()=>window.auditTimes.render=performance.now()-r);});
 const inventory=await page.evaluate(()=>{const app=window.auditApp;return {resolution:[app.graphicsDevice.width,app.graphicsDevice.height],pixelRatio:app.graphicsDevice.maxPixelRatio,vram:app.stats.vram,textures:[...app.graphicsDevice.textures].map(t=>({name:t.name,width:t.width,height:t.height,bytes:t.gpuSize})).sort((a,b)=>b.bytes-a.bytes).slice(0,20),lights:app.root.findComponents('light').filter(l=>l.enabled&&l.entity.enabled).map(l=>({name:l.entity.name,shadows:l.castShadows,resolution:l.shadowResolution})),meshes:app.root.findComponents('render').flatMap(r=>r.meshInstances.map(m=>({name:m.node.name,triangles:m.mesh.primitive[0].count/3}))).sort((a,b)=>b.triangles-a.triangles).slice(0,15)};});
 const samples=[];
 async function sample(name){await sleep(1500);const data=await page.evaluate(async()=>{const app=window.auditApp,rows=[];let renders=0;const rendered=()=>{renders++;rows.push({draws:app.graphicsDevice._drawCallsPerFrame,update:window.auditTimes.update,render:window.auditTimes.render});};app.on('postrender',rendered);const start=performance.now();for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,50));}app.off('postrender',rendered);return{renderedFps:renders*1000/(performance.now()-start),...Object.fromEntries(Object.keys(rows[0]||{draws:0,update:0,render:0}).map(k=>[k,rows.reduce((s,r)=>s+r[k],0)/Math.max(1,rows.length)])),resolution:[app.graphicsDevice.width,app.graphicsDevice.height]};});samples.push({name,...data});console.log(name,JSON.stringify(data));}
 await sample('house');await page.screenshot({path:out+'/house.png'});
 await page.evaluate(()=>{window.auditShadows=window.auditApp.root.findComponents('light').filter(l=>l.castShadows);window.auditShadows.forEach(l=>l.castShadows=false);});await sample('house-no-shadows');await page.evaluate(()=>window.auditShadows.forEach(l=>l.castShadows=true));
 await page.evaluate(()=>{const a=window.auditApp;window.auditRatio=a.graphicsDevice.maxPixelRatio;a.graphicsDevice.maxPixelRatio=1;const r=document.querySelector('#game').getBoundingClientRect();a.resizeCanvas(r.width,r.height);});await sample('house-resolution-1x');await page.evaluate(()=>{const a=window.auditApp;a.graphicsDevice.maxPixelRatio=window.auditRatio;const r=document.querySelector('#game').getBoundingClientRect();a.resizeCanvas(r.width,r.height);});
 await dev('store','corner');await sample('store');await dev('home');await dev('phase','night');await sample('night');await dev('play-pop');await sample('pop-menu');
 await writeFile(out+'/report.json',JSON.stringify({inventory,samples,errors,note:'Desktop headless browser at phone viewport; GPU/thermal measurements require physical phone.'},null,2));
}finally{await browser.close();}
