import {chromium} from 'file:///C:/Users/marc7/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.PILOT_URL||'http://127.0.0.1:5186/',label=process.env.PILOT_LABEL||'baseline';
await mkdir('pilot/evidence',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
const page=await context.newPage(),errors=[],checks=[],states=new Set();
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const snap=()=>page.evaluate(()=>window.__pilot.snapshot());
const cdp=await context.newCDPSession(page),touches=new Map();
async function touch(type,id,p){if(type==='touchEnd')touches.delete(id);else touches.set(id,{...p,id});await cdp.send('Input.dispatchTouchEvent',{type:type==='touchEnd'&&touches.size?'touchMove':type,touchPoints:[...touches.values()]});}
async function stick(){const b=await page.locator('#joystick').boundingBox();return {x:b.x+b.width/2,y:b.y+b.height/2,r:b.width*.29};}
async function moveTo(x,z){let s=await snap();const obstacles=s.obstacles,r=.265;const free=(x,z)=>Math.abs(x)<=3.3-r&&Math.abs(z)<=3.6-r&&!obstacles.some(o=>Math.abs(x-o.center[0])<=o.half[0]+r&&Math.abs(z-o.center[2])<=o.half[2]+r);
 const clear=(a,b)=>{const n=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.06);for(let i=1;i<=n;i++)if(!free(a[0]+(b[0]-a[0])*i/n,a[1]+(b[1]-a[1])*i/n))return false;return true;};
 const start=[s.position[0],s.position[2]],end=[x,z],step=.15,key=(x,z)=>x+','+z,open=[{x:Math.round(start[0]/step),z:Math.round(start[1]/step),g:0,f:0}],cost=new Map(),parents=new Map();let finish;
 if(clear(start,end))finish=null;else{while(open.length){open.sort((a,b)=>a.f-b.f);const c=open.shift(),p=[c.x*step,c.z*step];if(Math.hypot(p[0]-x,p[1]-z)<.3&&clear(p,end)){finish=c;break;}for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const nx=c.x+dx,nz=c.z+dz,np=[nx*step,nz*step],g=c.g+Math.hypot(dx,dz),k=key(nx,nz);if(!free(...np)||!clear(p,np)||g>=(cost.get(k)??Infinity))continue;cost.set(k,g);parents.set(k,c);open.push({x:nx,z:nz,g,f:g+Math.hypot(np[0]-x,np[1]-z)/step});}}assert.ok(finish,'route to '+end);}
 const path=[end];while(finish){path.unshift([finish.x*step,finish.z*step]);finish=parents.get(key(finish.x,finish.z));}path.unshift(start);const short=[];for(let i=0;i<path.length-1;){let j=path.length-1;while(j>i+1&&!clear(path[i],path[j]))j--;short.push(path[j]);i=j;}
 const c=await stick();await touch('touchStart',1,c);for(const target of short){const began=Date.now();let arrived=false;while(Date.now()-began<12000){s=await snap();states.add(s.animation);const dx=target[0]-s.position[0],dz=target[1]-s.position[2],d=Math.hypot(dx,dz);if(d<.13){arrived=true;break;}const R=s.cameraRight,F=s.cameraForward,mag=Math.min(1,Math.max(.4,d*3));await touch('touchMove',1,{x:c.x+c.r*(dx*R[0]+dz*R[2])/Math.hypot(R[0],R[2])/d*mag,y:c.y-c.r*(dx*F[0]+dz*F[2])/Math.hypot(F[0],F[2])/d*mag});await sleep(70);}assert.ok(arrived,'movement to '+target);}await touch('touchEnd',1);await sleep(100);
}
try{
 await page.goto(url);await page.waitForFunction(()=>window.__pilot?.snapshot().ready,undefined,{timeout:60000});await sleep(600);
 const initial=await snap();await page.screenshot({path:`pilot/evidence/${label}-390.png`});
 for(const[width,height]of[[320,568],[430,932],[390,844]]){await page.setViewportSize({width,height});await sleep(150);for(const id of['#joystick','#action-button','#pilot-reset']){const b=await page.locator(id).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=width&&b.y+b.height<=height,id+' fits');}await page.screenshot({path:`pilot/evidence/${label}-${width}.png`});}checks.push('320/390/430 phone controls fit');
 await moveTo(initial.book[0],initial.book[2]+.55);await page.locator('#action-button').tap();await page.waitForFunction(()=>window.__pilot.snapshot().carrying==='book');await page.waitForFunction(()=>!window.__pilot.snapshot().character.busy);await page.screenshot({path:`pilot/evidence/${label}-carrying.png`});checks.push('Touch pickup uses original carry system');
 const dest=(await snap()).destination;await moveTo(dest[0],dest[2]+.25);
 // Press the stick directly into the moved shelf; the original collision controller must stop before its footprint.
 const before=await snap(),c=await stick(),R=before.cameraRight,F=before.cameraForward;await touch('touchStart',1,c);await touch('touchMove',1,{x:c.x-c.r*R[2]/Math.hypot(R[0],R[2]),y:c.y+c.r*F[2]/Math.hypot(F[0],F[2])});await sleep(800);await touch('touchEnd',1);const after=await snap();const shelfCollider=after.obstacles.find(o=>Math.abs(o.center[0]-after.shelf[0])<.01&&Math.abs(o.center[2]-after.shelf[2])<.01);assert.ok(after.position[2]>=shelfCollider.center[2]+shelfCollider.half[2]+.235,'Shelf stops Arianna');checks.push('Collision stops joystick movement at shelf');
 await page.locator('#action-button').tap();await page.waitForFunction(()=>window.__pilot.snapshot().completed);await sleep(650);const complete=await snap();assert.ok(Math.hypot(...complete.book.map((n,i)=>n-complete.placement[i]))<.001);assert.deepEqual(complete.events,['pickup','placed']);await page.screenshot({path:`pilot/evidence/${label}-complete.png`});checks.push('Touch placement follows shelf child anchor');
 await page.reload();await page.waitForFunction(()=>window.__pilot?.snapshot().ready);const reload=await snap();assert.ok(reload.completed);assert.deepEqual(reload.shelf,initial.shelf);assert.ok(reload.saveKeys.includes('dumpling.editorPilot.book.v1'));assert.ok(!reload.saveKeys.some(k=>k.startsWith('arianna.')));checks.push('Disposable pilot save survives reload; real save keys absent');assert.deepEqual(errors,[]);assert.ok([...states].some(s=>s==='Run'));assert.ok([...states].some(s=>s==='CarryRun'));checks.push('Original Run and CarryRun observed');
 await writeFile(`pilot/evidence/${label}-report.json`,JSON.stringify({url,checks,errors,initial,complete,reload,animations:[...states]},null,2));console.log(JSON.stringify({checks,errors,shelf:initial.shelf,animations:[...states]}));
}catch(e){await page.screenshot({path:`pilot/evidence/${label}-failure.png`});console.error(e);console.error(JSON.stringify({errors,state:await snap().catch(()=>null)}));process.exitCode=1;}finally{await browser.close();}
