import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {browser,context,page,errors,checks,snap,sleep,pass,moveTo,dev,setPlanner} from './store-test-helpers.mjs';
await mkdir('artifacts/school',{recursive:true});
try{
 await page.goto('http://127.0.0.1:5191/dist/index.html');await page.waitForFunction(()=>window.__roomTest?.snapshot().characterLoaded,undefined,{timeout:90000});await dev('recess');let s=await snap();setPlanner(s.loop.recess);
 for(const seat of s.loop.recess.seats){await moveTo(seat.position);assert.equal(await page.locator('#action-button').getAttribute('data-target'),seat.id);await page.locator('#action-button').tap();await page.locator('#trading-dialog').waitFor({state:'visible'});await page.locator('#trade-cancel').tap();}pass('All three trading desks reachable with touch; dialogs still work');
 await moveTo([4.6,0,-6.3]);await page.screenshot({path:'artifacts/school/phone-classroom-door.png'});await moveTo([4.6,0,-8.5]);await moveTo([4.6,0,-14.8]);s=await snap();assert.equal(s.loop.recess.area,'Cafeteria');assert.equal(s.loop.mode,'recess');await page.screenshot({path:'artifacts/school/phone-cafeteria.png'});pass('Walk through classroom back doorway into cafeteria without teleporting');
 await moveTo([4.6,0,-19.1]);await page.screenshot({path:'artifacts/school/phone-lunch-counter.png'});await moveTo([4.6,0,-8.5]);await moveTo([4.6,0,-5.2]);await moveTo([0,0,3.3]);assert.equal((await snap()).loop.recess.area,'Classroom');pass('Lunch counter reachable and return through same doorway');
 const state=await page.evaluate(async()=>{const pc=await import('playcanvas'),a=pc.Application.getApplication();return {tex:a.stats.vram.tex,draws:a.stats.drawCalls.total};});await page.locator('#leave-recess').tap();await page.waitForFunction(()=>window.__roomTest.snapshot().loop.mode==='home');const hidden=await page.evaluate(async()=>{const pc=await import('playcanvas'),a=pc.Application.getApplication();return{player:a.root.findByName('Arianna').enabled,room:a.root.findByName('Maple cottage').enabled};});assert.deepEqual(hidden,{player:false,room:false});pass('School exit works; opening no longer shows Ariana or the bedroom');assert.deepEqual(errors,[]);await writeFile('artifacts/school/navigation-report.json',JSON.stringify({checks,errors,state},null,2));
}catch(e){await page.screenshot({path:'artifacts/school/navigation-failure.png'});await writeFile('artifacts/school/navigation-failure.json',JSON.stringify({error:String(e),errors,snapshot:await snap().catch(()=>null)},null,2));throw e;}finally{await browser.close();}
